name: petlar_landing_page
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/pet1.jpeg
    - assets/img/pet2.jpeg
    - assets/img/pet3.jpeg
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
    - family: DMSerifDisplay
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf


